- index.js
According to the [npm documentation](https://docs.npmjs.com/getting-started/updating-global-packages), the command to update a global package is `npm install -g packageName`.
I do not really know what `npm update -g packageName` does but I am sure it will not install the latest versio of the package.
Found when I tried to update bower.
> fix update command

- index.js
We rewrite `options.pkg` to hold only the information we need (name and version). So when we call node with check.js we no longer pass the entire content of package.json as a command line argument.
This resolves #57.
> Use minimal pkg instead of the full package.json content

- readme.md
The number of modules pulling update-notifier in as a dependency has ballooned from 100+ to [600+](https://www.npmjs.com/browse/depended/update-notifier?offset=606)
> Update number of update-notifier dependencies

- package.json
This PR addresses issue #72.
According to the [release notes of configstore](https://github.com/yeoman/configstore/releases/tag/v2.0.0), there has been added support for dot notations. Since update-notifier does not use dots in its config values, this should be fine by just changing the referenced version.
> Change configstore dependency version to 2.0.0

- check.js
- index.js
- package.json
- test.js
Fixes #76.
Catches any error thrown from `configstore` synchronous fs access and gracefully handles it by short-circuiting the update check (via undefined `config`) and printing a pretty notification on process exit.
The notification gives the user suggestions to fix the problem and looks something like this (centered horizontally in boxen):
Also added a test, which works based on the assumptions that:
- You're not running as the root user
- Access to `/usr` requires root access
If the assumptions are not met, the test will fail.
A few other things to note:
1. The notification suggestions are static (**not** platform-specific).
2. I'm not sure how safe the `chown` suggestion is.
3. In order to output the correct `configstore` directory, I added `xdg-basedir` as a direct dependency, but my …
> feat: handle configstore error gracefully

- index.js
Fixes #74.
The extra newline is to leave a space after the `^C` that written into the console buffer when you ctrl+C. (I know there's already a newline at the start of `message`, but it needs two in the case of a sigint otherwise it appears to start on the line immediately following `^C`.)
> Show deferred message on SIGINT as well as exit

- index.js
- package.json
- test.js
Replace the explicit use of `ansi-align` with the new `align: 'center'` option [available in `boxen@0.6.0`](https://github.com/sindresorhus/boxen/tree/v0.6.0#align).
Add center-alignment for the default `.notify()` message, with test to verify output.
The "update check failed" message used when `configstore` throws was already center-aligned, but this PR will defer alignment to `boxen`.
> feat: center-align message via boxen@0.6.0

- readme.md
Just a minor tweak to "correct" the default `options.boxenOpts` listed in the readme. This only came about because #83 and #84 were developed separately in parallel.
Note that we _may_ want to update the screenshot to show center alignment (first line would move to the right by one space). If I could produce terminal output that looked that good, I would do this myself, but I can't get the box to look quite right.
> docs: add align: 'center' to default boxenOpts

- readme.md
Sorry, just noticed the header level for `options.boxenOpts` was inconsistent in the readme. Silly, I know, but I couldn't let it go.
> docs: h3 -> h4 for options.boxenOpts

- index.js
`opts.defer` would only defer on `undefined`, but docs state it defaults to true, where true doesn't actually defer.
> fix opts.defer

- check.js
- package.json
- the "xo/no-process-exit" rule is now "unicorn/no-process-exit", so fix an "eslint-disable" line to prevent lint errors
- xo itself requires Node 4.x or newer now (at least according to the thrown errors), so change `npm test` so that it only executes `xo` for compatible Node versions
> get tests passing on Travis CI with latest xo, etc

- index.js
Fix for typicode/json-server#425
#75 Adds a handler for SIGINT that prints out the update message, but forgets to exit the process. That means that whenever you press control-c to stop your program from running, it prints out a nice update message and continues to run.
This PR fixes the problem by calling `process.exit()` in the SIGINT handler. Since the process' `'exit'` handler already prints out the update message, the SIGINT handler doesn't need to. The SIGINT handler still prints out a newline character as in #75.
> Exit process on SIGINT

- .travis.yml
- package.json
Also update dependencies.
Would you like to postpone this until a version of `configstore` with https://github.com/yeoman/configstore/pull/49 merged is published?
> Bump minimum supported `node` version to `node@4`.

- index.js
- readme.md
- test.js
In cases where your CLI package also serves a secondary purpose as a dependency of a project (e.g. the new crop of single-dependency toolkits such as [nwb](https://github.com/insin/nwb)), the default update message shouldn't be recommending a global npm install.
With this new option (`isGlobal`), the default behaviour stays the same, but it is now configurable. Of course, this has always been possible when using the `message` argument, but it's a shame for authors to lose out on the pretty boxen output when they just want to change a flag.
I've updated the tests to ensure this output is correct, but they could use a little refactoring now that more than one test uses a similar `UpdateNotifier` sub-class.
> Add option to exclude `-g` argument from default update message

- index.js
- test.js
Avoids initializing configStore and showing related errors if environment variable or argv disables notifier.
Rel #107
> Bail if notify is disabled

- index.js
- package.json
- test/notify.js
> Add is-installed-globally for auto-detection

- index.js
- package.json
- readme.md
- test/update-notifier.js
I don't think it makes sense to run on CI. 
Hopefully this won't mess up update-notifier's own tests
https://ci.appveyor.com/project/lerna/lerna/build/1.0.1114/job/wry5k8q54m1qrw1c#L765
> Disable on CI

- package.json
Just surfing across my node_modules and found this:
I add `https://` and VSCode no longer complaining about it.
> Fix URI Scheme in package.json

- index.js
- package.json
- readme.md
- test/notify.js
My team and I have run into multiple scenarios where we've wanted to output the update message when running as an npm script.  To do this, we've had to dig through the source code, hack environment variables, run this package, and reset environment variables.
This PR include functionality to bypass the isNpm() check.  This will not break any existing functionality.
---
Fixes #122
> Add ability to bypass isNpm check with `shouldNotifyInNpmScript` option

- readme.md
Now, `shouldNotifyInNpmScript` is described as an notify option in the Documentation, but, looking at the source code it's an option from `constructor`: https://github.com/yeoman/update-notifier/blob/master/index.js#L43
Just move `shouldNotifyInNpmScript` for correct place in documentation.
> Fix docs position of `shouldNotifyInNpmScript`

- test/notify.js
This test will be fixed when AVA upgrade `update-notifier` to the next version.
> Add failing test for #153

- package.json
- test/notify.js
> Fix failing test

- index.js
- package.json
Low priority fix: Change object spread back to `Object.assign` since engine.node is >=8.
Another package on node 8 dependent on update-notifier was failing at the `notify()` script with `Unexpected token ...` and not showing their "please upgrade node" warning. [Node>=8.6 compiled ok](https://node.green/#ES2018-features-object-rest-spread-properties-object-spread-properties), but everything below that resulted in the same error. Was going to open an issue there and PR, but decided just to PR here because there's only one instance of the object spreading and seemed like a better fix in case any other users were using lower 8x versions.
xo default rule is "error" on `prefer-object-spread` (which I'm sure you're aware as a member), so I turned that rule off in package.json to complete the …
> Remove object spread to support node >=8.0.0 <8.6.0

- readme.md
Updates the [doc's external link](https://github.com/yeoman/update-notifier/blob/master/readme.md#notifiernotifyoptions) to nodejs website on TTY context to match their current section title, changed in [this commit](https://github.com/nodejs/node/commit/5ba00af2170e58e29ac985038b335253fdd39d9f?short_path=3025128#diff-eaa7a086b3a1bc26c044f11e69800239L1571).
> Docs: Update URL to 'TTY' 

- index.js
- readme.md
- test/update-notifier.js
Fixes #171.
This disables `update-notifier` when the `NODE_ENV` environment variable is `test`, for example during unit tests.
> Disable when `NODE_ENV` is `test`

- index.js
- test/notify.js
Fixes https://github.com/yeoman/update-notifier/issues/60
That bug exists because `update-notifier` caches the current version on first run and then notifies about it on the following one, without checking again which version is currently installed.
This PR now also fixes the value returned as `notifier.update.current`, which was previously just the cached version rather than the real current version (_real_ => from the currently-installed `package.json`)
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#60: When run right after npm install, a wrong version is displayed](https://issuehunt.io/repos/7069389/issues/60)
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members) …
> Avoid showing notification if current version is the latest

- check.js
- index.js
- readme.md
- test/update-notifier.js
Just deprecate the `callback` option as https://github.com/yeoman/update-notifier/issues/85#issuecomment-279421079 mentioned.
It's a breaking change.
> Remove the `callback` option

- index.js
- test/notify.js
&nbsp; | Before | After
--- | --- | ---
`defer: true` (default) | <img width="318" alt="Screen Shot 2020-07-24 at 2 28 07 AM" src="https://user-images.githubusercontent.com/113730/88366023-eb311c80-cd55-11ea-9bee-1cc32ee949c2.png"> | <img width="331" alt="Screen Shot 2020-07-24 at 2 28 54 AM" src="https://user-images.githubusercontent.com/113730/88366041-fa17cf00-cd55-11ea-8402-cbd938c43471.png">
`defer: false` | <img width="322" alt="Screen Shot 2020-07-24 at 2 28 33 AM" src="https://user-images.githubusercontent.com/113730/88366029-f1bf9400-cd55-11ea-8e02-9a9bcbac3661.png"> | <img width="328" alt="Screen Shot 2020-07-24 at 2 29 17 AM" src="https://user-images.githubusercontent.com/113730/88366057-03a13700-cd56-11ea-8a3b-1263328a6c27.png">
Interestingly, while it doesn't feel that way on …
> Improve vertical alignment of the notifier output

- readme.md
Pageres is mentioned as an example where update-notifier is used.
They are no longer using it.
> Remove a project from "Users" section

- index.js
- package.json
- test/notify.js
Fixes #181 
I haven't investigated why this would happen in the first place, but I guess it could if you install a beta version.
Is that a bug in https://github.com/sindresorhus/latest-version?
> Don't suggest to upgrade to lower version

- package.json
Fix just released in v7.0.0 of latest-version, which no longer uses a package that then again depends in a vulnerable version of `got` package.
@sindresorhus Could you approve workflow run and merge when you have time? This package already requires Node 14, so we should be good2go.
> Bump 'latest-version' package to fix security vulnerability in subdependency

- package.json
- update-notifier.js
- Replaces and closes #232 
Before: 80 deps https://npmgraph.js.org/?q=https://raw.githubusercontent.com/yeoman/update-notifier/b4840e5a4aa66b80233c095595708853d188520c/package.json
After: 59 deps https://npmgraph.js.org/?q=https%3A%2F%2Fraw.githubusercontent.com%2Fyeoman%2Fupdate-notifier%2Fdad8beac208d623451c99bd59c8e940e36c2ddaa%2Fpackage.json
> Update all dependencies

- package.json
- update-notifier.js
It looks like this initially used semver-diff, but then loaded the whole of semver, making the former redundant.
This PR drops semver-diff and avoids the [`index` file](https://x.com/iamakulov/status/1331551351214645251) import from semver.
> Drop redundant dependency

- update-notifier.js
ref: #98
ref: #75
Hello and thank you for your work!
I noticed that this project implemented a feature in #75 that show a update message when a SIGINT signal is emitted, however, in #98, the update message is removed and the process is exited.
Then there is no longer any need to register a SIGINT listener, and a SIGINT listener registered here would prevent the user from registering a SIGINT listener of their own.
For example:
In my project, I registered my own SIGINT listener in Serve to be able to kill script-started processes when Ctrl+C is pressed. However, since update-notifier has already registered the SIGINT listener and update-notifier always runs before my code, my SIGINT listener never takes effect unless I use `process.removeAllListeners(“SIGINT”);`. This is very inelegant, …
> Remove unused SIGINT listener
